# Generated by Django 3.2.8 on 2021-10-11 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('choiceId', models.IntegerField(primary_key=True, serialize=False)),
                ('questionId', models.IntegerField()),
                ('choice', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionId', models.IntegerField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('questionType', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('choiceId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.choices')),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.questions')),
            ],
            options={
                'unique_together': {('name', 'questionId', 'choiceId')},
            },
        ),
    ]
