# Generated by Django 3.2.8 on 2021-10-12 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20211011_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='label',
            field=models.CharField(default='amend_this', max_length=255),
            preserve_default=False,
        ),
    ]
