# Generated by Django 3.2.8 on 2021-10-12 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_choice_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='choiceId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='answer',
            name='questionId',
            field=models.IntegerField(),
        ),
    ]
